name: thopaa
description: "Live Blood Donation App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6



  # COMMON
  nb_utils: ^7.0.3
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5


  # FIREBASE
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.2
  firebase_auth: ^4.19.2
  firebase_storage: ^11.7.2
  cloud_firestore: ^4.17.0

  # FIREBASE MESSAGING
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.0
  
  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  lottie:

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.10+1

  # IMAGE
  image_picker: ^1.0.7
  photo_view: ^0.14.0

  # OTHER
  country_picker: ^2.0.25
  flutter_custom_tabs: ^2.0.0+1
  permission_handler: ^11.3.1
  flutter_html: ^3.0.0-beta.2
  firebase_pagination: ^3.1.0
  webview_flutter: ^4.7.0
  file_picker: ^6.2.0

  # MAP
  google_maps_flutter: ^2.6.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1


  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl:
  flutter_plugin_android_lifecycle:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/lottie/
